### ISSUE TITLE
organizational stuff

### ISSUE THREAD

**Issue by aammd** [aurielfournier/science_borealis_stats_math#3]
hi @aurielfournier ! Right now I'm working on my own fork of this repository. It seems to be working well! However it might be even smoother to use branches, rather than forks. That would allow me to sometimes make edits here directly, though we could still use pull requests when we want to discuss something. What do you think? 
to use that approach, you'd have to first add me here as a collaborator :smile_cat:

**Comment by aurielfournier** [comment]
good call :) done!
